In [2]:
import torch
# 입력층이 2개, 은닉층이 3개 출력층이 2개 인 경우
# 입력층 뉴런이 [2,1]
x = torch.tensor([2,1])
# 입력층의 가중치가 [3,2],[2,-3],[-4,1] 이고, 바이어스가 1
w1 = torch.tensor([[3,2,-4],[2,-3,1]])
b1 = 1
# 은닉층의 가중치가 [-1,1,3],[1,2,1] 이고, 바이어스가 -1
w2 = torch.tensor([[-1,1],[1,2],[3,1]])
b2 = -1

In [3]:
h_preact = torch.matmul(x, w1) + b1
h = torch.nn.functional.relu(h_preact)
y = torch.matmul(h, w2) + b2

In [4]:
h_preact

tensor([ 9,  2, -6])

In [5]:
h

tensor([9, 2, 0])

In [6]:
y

tensor([-8, 12])