In [2]:
import torch
input = torch.tensor([[1.0, 2.0, 3.0],[1.0, 1.0, 1.0]])
# m.weight (gamma), m.bias (beta) 를 1,0 으로 초기화
m = torch.nn.LayerNorm(input.shape[-1])
output = m(input)

In [3]:
output

tensor([[-1.2247,  0.0000,  1.2247],
        [ 0.0000,  0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)

In [4]:
m.weight

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)

In [5]:
m.bias

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)